# Generated by Django 3.0.7 on 2021-12-05 09:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=200, null=True)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, null=True, size=None)),
                ('country_of_origin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sponsors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None)),
                ('target_countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None)),
                ('techniques_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None)),
                ('tools_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=None, null=True, size=None)),
                ('further_information', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=None, null=True, size=None)),
                ('operations_performed', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('refernces', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
